/**
 * Configuration for the Section Three "category showcase" animation.
 *
 * Nothing here is hardcoded into the component — edit this file to change
 * background text, images, sizes, positions, rotation, scale, layering or
 * scroll pacing. Each category gets one "beat" of the scroll timeline
 * (see SCROLL_VH_PER_CATEGORY in useCategoryScroll.ts / page.tsx).
 *
 * Coordinate system for `settle` (and the implicit entry/exit derived from it):
 *  - top / left are percentages of the stage (0-100), measured from the
 *    stage's top-left corner, and refer to the CENTER of the card.
 *  - width / height are in pixels at the desktop reference size (the stage
 *    scales down proportionally on smaller viewports via CSS clamp/vw so the
 *    composition doesn't need to be redefined, only the mobile layout below
 *    is a deliberately different arrangement per the brief).
 *  - layer: "front" cards render above the big text, "back" cards render
 *    below it (this is what makes the text look covered in some places and
 *    revealed in others).
 *  - from: the direction each card travels in from / exits back out to.
 *    Purely additive offsets (in px) applied at t=0 and t=1 of the card's
 *    own local progress.
 *  - speed: relative scrub speed multiplier for the settle->drift phase
 *    (1 = normal, <1 = slower/lagging, >1 = faster/leading) so cards never
 *    move in lockstep.
 *  - rotate/scale: settle-state rotation (deg) and scale; entry/exit add a
 *    delta on top of these (see ANIM constants in useCategoryScroll.ts).
 */

export type CardConfig = {
    id: string;
    src: string;
    alt: string;
    width: number;
    height: number;
    top: number;
    left: number;
    layer: "front" | "back";
    rotate: number;
    scale: number;
    from: { x: number; y: number };
    speed: number;
    driftAmplitude: number;
    driftPhase: number;
};

export type MobileCardConfig = Omit<CardConfig, "width" | "height"> & {
    width: number;
    height: number;
};

export type CategoryScene = {
    id: string;
    label: string;
    word: string;
    background: string;
    textColor: string;
    accent: string;
    cards: CardConfig[];
    mobileCards: MobileCardConfig[];
};

export const CATEGORY_SCENES: CategoryScene[] = [
    {
        id: "decor",
        label: "Decor",
        word: "Decor",
        background: "#6b685e",
        textColor: "#d9d5c9",
        accent: "#f2ede0",
        cards: [
            {
                id: "decor-chair",
                src: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=1000&auto=format&fit=crop",
                alt: "Terracotta lounge chair against a sage wall",
                width: 300,
                height: 300,
                top: 18,
                left: 82,
                layer: "front",
                rotate: -2,
                scale: 1,
                from: { x: 260, y: -160 },
                speed: 0.85,
                driftAmplitude: 18,
                driftPhase: 0.2,
            },
            {
                id: "decor-lamp",
                src: "https://images.unsplash.com/photo-1543198126-b7b7d5a7f7b2?q=80&w=800&auto=format&fit=crop",
                alt: "Sculptural boucle table lamp",
                width: 260,
                height: 340,
                top: 62,
                left: 12,
                layer: "front",
                rotate: 3,
                scale: 1,
                from: { x: -220, y: 180 },
                speed: 1.1,
                driftAmplitude: 14,
                driftPhase: 1.4,
            },
            {
                id: "decor-nightstand",
                src: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?q=80&w=800&auto=format&fit=crop",
                alt: "Nightstand lamp glowing beside a starry window",
                width: 190,
                height: 190,
                top: 56,
                left: 60,
                layer: "back",
                rotate: -4,
                scale: 1,
                from: { x: 120, y: 140 },
                speed: 1.35,
                driftAmplitude: 22,
                driftPhase: 2.6,
            },
            {
                id: "decor-frame",
                src: "https://images.unsplash.com/photo-1615529182904-14819c35db37?q=80&w=800&auto=format&fit=crop",
                alt: "Framed still life leaning on a shelf",
                width: 150,
                height: 150,
                top: 92,
                left: 24,
                layer: "front",
                rotate: 6,
                scale: 0.95,
                from: { x: -140, y: -200 },
                speed: 0.7,
                driftAmplitude: 10,
                driftPhase: 3.3,
            },
        ],
        mobileCards: [
            {
                id: "decor-chair-m",
                src: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800&auto=format&fit=crop",
                alt: "Terracotta lounge chair against a sage wall",
                width: 168,
                height: 168,
                top: 14,
                left: 76,
                layer: "front",
                rotate: -3,
                scale: 1,
                from: { x: 140, y: -90 },
                speed: 0.85,
                driftAmplitude: 10,
                driftPhase: 0.2,
            },
            {
                id: "decor-lamp-m",
                src: "https://images.unsplash.com/photo-1543198126-b7b7d5a7f7b2?q=80&w=700&auto=format&fit=crop",
                alt: "Sculptural boucle table lamp",
                width: 150,
                height: 190,
                top: 66,
                left: 20,
                layer: "front",
                rotate: 3,
                scale: 1,
                from: { x: -120, y: 110 },
                speed: 1.1,
                driftAmplitude: 8,
                driftPhase: 1.4,
            },
            {
                id: "decor-nightstand-m",
                src: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?q=80&w=700&auto=format&fit=crop",
                alt: "Nightstand lamp glowing beside a starry window",
                width: 118,
                height: 118,
                top: 46,
                left: 66,
                layer: "back",
                rotate: -4,
                scale: 1,
                from: { x: 90, y: 90 },
                speed: 1.3,
                driftAmplitude: 12,
                driftPhase: 2.6,
            },
        ],
    },
    {
        id: "office",
        label: "Office",
        word: "Office",
        background: "#ded6c8",
        textColor: "#2c2924",
        accent: "#171512",
        cards: [
            {
                id: "office-desk",
                src: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=1000&auto=format&fit=crop",
                alt: "Wall-mounted floating desk with a laptop",
                width: 290,
                height: 340,
                top: 42,
                left: 84,
                layer: "front",
                rotate: 2,
                scale: 1,
                from: { x: 240, y: 60 },
                speed: 0.9,
                driftAmplitude: 16,
                driftPhase: 0.6,
            },
            {
                id: "office-chairs",
                src: "https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=800&auto=format&fit=crop",
                alt: "Pair of bentwood dining chairs",
                width: 240,
                height: 200,
                top: 16,
                left: 44,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: -60, y: -220 },
                speed: 1.2,
                driftAmplitude: 12,
                driftPhase: 1.9,
            },
            {
                id: "office-pencil",
                src: "https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=700&auto=format&fit=crop",
                alt: "Pencil resting on a wooden desk",
                width: 170,
                height: 100,
                top: 10,
                left: 8,
                layer: "front",
                rotate: -5,
                scale: 1,
                from: { x: -200, y: -100 },
                speed: 0.75,
                driftAmplitude: 20,
                driftPhase: 2.8,
            },
        ],
        mobileCards: [
            {
                id: "office-desk-m",
                src: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?q=80&w=800&auto=format&fit=crop",
                alt: "Wall-mounted floating desk with a laptop",
                width: 180,
                height: 210,
                top: 46,
                left: 78,
                layer: "front",
                rotate: 2,
                scale: 1,
                from: { x: 140, y: 40 },
                speed: 0.9,
                driftAmplitude: 10,
                driftPhase: 0.6,
            },
            {
                id: "office-chairs-m",
                src: "https://images.unsplash.com/photo-1503602642458-232111445657?q=80&w=700&auto=format&fit=crop",
                alt: "Pair of bentwood dining chairs",
                width: 160,
                height: 130,
                top: 14,
                left: 34,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: -40, y: -140 },
                speed: 1.2,
                driftAmplitude: 8,
                driftPhase: 1.9,
            },
        ],
    },
    {
        id: "tech",
        label: "Tech",
        word: "Tech",
        background: "#211f1b",
        textColor: "#eee9dd",
        accent: "#e7c98a",
        cards: [
            {
                id: "tech-speaker",
                src: "https://images.unsplash.com/photo-1589003077984-894e133dabab?q=80&w=1000&auto=format&fit=crop",
                alt: "Sculptural black speaker on a shelf",
                width: 300,
                height: 340,
                top: 30,
                left: 14,
                layer: "front",
                rotate: -2,
                scale: 1,
                from: { x: -260, y: -140 },
                speed: 0.85,
                driftAmplitude: 16,
                driftPhase: 0.3,
            },
            {
                id: "tech-camera",
                src: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
                alt: "Retro-styled compact camera",
                width: 150,
                height: 190,
                top: 20,
                left: 62,
                layer: "front",
                rotate: 4,
                scale: 1,
                from: { x: 200, y: -160 },
                speed: 1.15,
                driftAmplitude: 14,
                driftPhase: 1.7,
            },
            {
                id: "tech-phone",
                src: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=800&auto=format&fit=crop",
                alt: "Smart speaker with a soft round grille",
                width: 210,
                height: 260,
                top: 88,
                left: 40,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: 40, y: 220 },
                speed: 1.3,
                driftAmplitude: 20,
                driftPhase: 3.1,
            },
            {
                id: "tech-panel",
                src: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?q=80&w=800&auto=format&fit=crop",
                alt: "Minimal pale device on a desk",
                width: 260,
                height: 150,
                top: 82,
                left: 88,
                layer: "front",
                rotate: 2,
                scale: 0.95,
                from: { x: 220, y: 180 },
                speed: 0.7,
                driftAmplitude: 12,
                driftPhase: 2.2,
            },
        ],
        mobileCards: [
            {
                id: "tech-speaker-m",
                src: "https://images.unsplash.com/photo-1589003077984-894e133dabab?q=80&w=800&auto=format&fit=crop",
                alt: "Sculptural black speaker on a shelf",
                width: 176,
                height: 200,
                top: 16,
                left: 22,
                layer: "front",
                rotate: -2,
                scale: 1,
                from: { x: -140, y: -90 },
                speed: 0.85,
                driftAmplitude: 8,
                driftPhase: 0.3,
            },
            {
                id: "tech-camera-m",
                src: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=700&auto=format&fit=crop",
                alt: "Retro-styled compact camera",
                width: 118,
                height: 150,
                top: 12,
                left: 70,
                layer: "front",
                rotate: 4,
                scale: 1,
                from: { x: 120, y: -100 },
                speed: 1.15,
                driftAmplitude: 8,
                driftPhase: 1.7,
            },
            {
                id: "tech-phone-m",
                src: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=700&auto=format&fit=crop",
                alt: "Smart speaker with a soft round grille",
                width: 150,
                height: 180,
                top: 74,
                left: 60,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: 30, y: 140 },
                speed: 1.25,
                driftAmplitude: 10,
                driftPhase: 3.1,
            },
        ],
    },
    {
        id: "furniture",
        label: "Furniture",
        word: "Furniture",
        background: "#e7e0d3",
        textColor: "#211e19",
        accent: "#8a6a4f",
        cards: [
            {
                id: "furniture-curtain",
                src: "https://images.unsplash.com/photo-1616627561950-9f746e330187?q=80&w=800&auto=format&fit=crop",
                alt: "Sheer curtains beside a wooden bench",
                width: 210,
                height: 320,
                top: 68,
                left: 10,
                layer: "front",
                rotate: -2,
                scale: 1,
                from: { x: -180, y: 200 },
                speed: 0.8,
                driftAmplitude: 14,
                driftPhase: 0.5,
            },
            {
                id: "furniture-chair",
                src: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800&auto=format&fit=crop",
                alt: "Warm terracotta lounge chair",
                width: 150,
                height: 190,
                top: 20,
                left: 46,
                layer: "back",
                rotate: 3,
                scale: 1,
                from: { x: 0, y: -220 },
                speed: 1.2,
                driftAmplitude: 12,
                driftPhase: 2.0,
            },
            {
                id: "furniture-side-table",
                src: "https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=800&auto=format&fit=crop",
                alt: "Round side table styled with small objects",
                width: 230,
                height: 190,
                top: 76,
                left: 62,
                layer: "front",
                rotate: -4,
                scale: 1,
                from: { x: 200, y: 160 },
                speed: 1.05,
                driftAmplitude: 18,
                driftPhase: 3.4,
            },
            {
                id: "furniture-shelf",
                src: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800&auto=format&fit=crop",
                alt: "Minimal shelf styling detail",
                width: 260,
                height: 150,
                top: 12,
                left: 86,
                layer: "front",
                rotate: 2,
                scale: 0.95,
                from: { x: 220, y: -140 },
                speed: 0.7,
                driftAmplitude: 10,
                driftPhase: 1.1,
            },
        ],
        mobileCards: [
            {
                id: "furniture-curtain-m",
                src: "https://images.unsplash.com/photo-1616627561950-9f746e330187?q=80&w=700&auto=format&fit=crop",
                alt: "Sheer curtains beside a wooden bench",
                width: 150,
                height: 210,
                top: 66,
                left: 18,
                layer: "front",
                rotate: -2,
                scale: 1,
                from: { x: -120, y: 130 },
                speed: 0.8,
                driftAmplitude: 8,
                driftPhase: 0.5,
            },
            {
                id: "furniture-side-table-m",
                src: "https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=700&auto=format&fit=crop",
                alt: "Round side table styled with small objects",
                width: 156,
                height: 128,
                top: 74,
                left: 66,
                layer: "front",
                rotate: -4,
                scale: 1,
                from: { x: 130, y: 100 },
                speed: 1.05,
                driftAmplitude: 10,
                driftPhase: 3.4,
            },
            {
                id: "furniture-chair-m",
                src: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=700&auto=format&fit=crop",
                alt: "Warm terracotta lounge chair",
                width: 110,
                height: 140,
                top: 16,
                left: 50,
                layer: "back",
                rotate: 3,
                scale: 1,
                from: { x: 0, y: -140 },
                speed: 1.2,
                driftAmplitude: 8,
                driftPhase: 2.0,
            },
        ],
    },
    {
        id: "lighting",
        label: "Lighting",
        word: "Lighting",
        background: "#22261f",
        textColor: "#e7e3d6",
        accent: "#c9b48a",
        cards: [
            {
                id: "lighting-mushroom",
                src: "https://images.unsplash.com/photo-1543198126-b7b7d5a7f7b2?q=80&w=1000&auto=format&fit=crop",
                alt: "Boucle mushroom table lamp glowing softly",
                width: 260,
                height: 320,
                top: 22,
                left: 80,
                layer: "front",
                rotate: 2,
                scale: 1,
                from: { x: 220, y: -160 },
                speed: 0.9,
                driftAmplitude: 16,
                driftPhase: 0.4,
            },
            {
                id: "lighting-pendant",
                src: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?q=80&w=800&auto=format&fit=crop",
                alt: "Warm pendant light fixture",
                width: 190,
                height: 240,
                top: 66,
                left: 16,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: -200, y: 180 },
                speed: 1.2,
                driftAmplitude: 14,
                driftPhase: 1.6,
            },
            {
                id: "lighting-sconce",
                src: "https://images.unsplash.com/photo-1631679706909-1844bbd07221?q=80&w=800&auto=format&fit=crop",
                alt: "Wall sconce beside a night window",
                width: 170,
                height: 170,
                top: 12,
                left: 44,
                layer: "front",
                rotate: 4,
                scale: 0.95,
                from: { x: -40, y: -200 },
                speed: 0.75,
                driftAmplitude: 20,
                driftPhase: 2.7,
            },
        ],
        mobileCards: [
            {
                id: "lighting-mushroom-m",
                src: "https://images.unsplash.com/photo-1543198126-b7b7d5a7f7b2?q=80&w=800&auto=format&fit=crop",
                alt: "Boucle mushroom table lamp glowing softly",
                width: 168,
                height: 200,
                top: 18,
                left: 74,
                layer: "front",
                rotate: 2,
                scale: 1,
                from: { x: 130, y: -100 },
                speed: 0.9,
                driftAmplitude: 8,
                driftPhase: 0.4,
            },
            {
                id: "lighting-pendant-m",
                src: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?q=80&w=700&auto=format&fit=crop",
                alt: "Warm pendant light fixture",
                width: 130,
                height: 168,
                top: 68,
                left: 22,
                layer: "back",
                rotate: -3,
                scale: 1,
                from: { x: -110, y: 110 },
                speed: 1.2,
                driftAmplitude: 8,
                driftPhase: 1.6,
            },
        ],
    },
];

/** How many vh each category gets to play out its full enter/hold/exit cycle. */
export const SCROLL_VH_PER_CATEGORY = 100;